//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2007 - Infos @ http://www.17buddies.net //
//          More than 15000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
//
// Res file generated by mikado for 17Buddies.
//
// Map Name  :cs_poolmansion  
//
//  
//////////////////////////////////////////////////////////
graffi.wad
graffi2.wad
tree.wad
 
gfx/env/citybk.tga
gfx/env/citydn.tga
gfx/env/cityft.tga
gfx/env/citylf.tga
gfx/env/cityrt.tga
gfx/env/cityup.tga
 
models/scientist.mdl

sound/ambience/biggun2.wav
sound/ambience/biggun3.wav

sprites/muzzleflash2.spr
 