//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2007 - Infos @ http://www.17buddies.net //
//          More than 15000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
//
// Res file generated by mikado for 17Buddies.
//
// Map Name  : de_dust2_christmas
//
// Download @: http://dwl.17buddies.net/link/map/12897/de_dust2_christmas.html
//
//////////////////////////////////////////////////////////
 
as_tundra.wad
bjchristmas.wad
 
gfx/env/snowup.tga
gfx/env/snowdn.tga
gfx/env/snowlf.tga
gfx/env/snowrt.tga
gfx/env/snowft.tga
gfx/env/snowbk.tga

models/mil_crategibs.mdl
models/smann.mdl
models/wbaum.mdl
models/gesch2.mdl
models/gesch1.mdl

sprites/glow04.spr
