// de_mangashop
// RESGen is made by Jeroen "ShadowLord" Bogers,
// modified by Xale

// .res entries :
maps/de_mangashop.txt
de_mangashop.wad
models/3dm_pc2.mdl
models/buzz/buzzer_pa_car2.mdl
models/city_map/fire_hydrant.mdl
models/city_map/pi_tree1.mdl
models/city_map/pi_tree2.mdl
models/city_map/pi_tree3.mdl
models/city_map/xen_ac.mdl
models/cs_church_newb/haxe.mdl
models/cs_church_newb/huhn.mdl
models/cs_paris/cs_paris_seat.mdl
models/de_austria_models/apfel.mdl
models/de_austria_models/charles.mdl
models/de_austria_models/souther.mdl
models/de_flow/hessi_tonne.mdl
models/de_flow/moby_barracade.mdl
models/de_mangashop/can_cola.mdl
models/de_mangashop/car_audi80.mdl
models/de_mangashop/car_dolo.mdl
models/de_mangashop/cellphone.mdl
models/de_mangashop/chair_stool.mdl
models/de_mangashop/char/batmanbeyond.mdl
models/de_mangashop/char/db5.mdl
models/de_mangashop/char/iron-man.mdl
models/de_mangashop/char/kunai_tag.mdl
models/de_mangashop/char/rocklee.mdl
models/de_mangashop/char/sasuke.mdl
models/de_mangashop/char/shuriken.mdl
models/de_mangashop/char/spawn.mdl
models/de_mangashop/char/spiderman.mdl
models/de_mangashop/char/vegeta.mdl
models/de_mangashop/computer.mdl
models/de_mangashop/futon.mdl
models/de_mangashop/gibs_anime2.mdl
models/de_mangashop/goomba.mdl
models/de_mangashop/kirby.mdl
models/de_mangashop/kirby_feather.mdl
models/de_mangashop/lamp_euro_sx15.mdl
models/de_mangashop/pocketpc.mdl
models/de_mangashop/rub.mdl
models/de_mangashop/rub_feather.mdl
models/de_mangashop/set_soccer_shop.mdl
models/de_mangashop/shaver.mdl
models/de_mangashop/sink.mdl
models/de_mangashop/sitting2.mdl
models/de_mangashop/starwars/darkvador.mdl
models/de_mangashop/starwars/darthmaul.mdl
models/de_mangashop/starwars/stormtrooper.mdl
models/de_mangashop/toilet_plunger.mdl
models/de_mangashop/toilette.mdl
models/gibs_anime.mdl
models/industrywest/gins_bucket.mdl
models/industrywest/gins_clawhammerot.mdl
models/industrywest/gins_couch.mdl
models/industrywest/gins_deskchair.mdl
models/industrywest/gins_leafy.mdl
models/industrywest/gins_lunch_sack.mdl
models/industrywest/gins_mug.mdl
models/industrywest/gins_papersmags.mdl
models/industrywest/gins_shelvesA.mdl
models/industrywest/gins_trashcan.mdl
models/p_b_lightsabre.mdl
models/p_r_lightsabre.mdl
models/props/bathroom_handdryer.mdl
models/props/bathroom_toilet.mdl
models/props/bathroom_toilet_dirty.mdl
models/props/bathroom_urinal.mdl
models/props/bomb_fastline_closed.mdl
models/props/bush_evergreen.mdl
models/props/bush_japan_bush01.mdl
models/props/cash_register.mdl
models/props/cashregister.mdl
models/props/chair_office.mdl
models/props/chair_stool.mdl
models/props/coat_rack.mdl
models/props/coffee_maker.mdl
models/props/composite_drug-beakers.mdl
models/props/couch_blue.mdl
models/props/deadguy_euro.mdl
models/props/deskc_ritual.mdl
models/props/deskl_ritual.mdl
models/props/desks_ritual.mdl
models/props/dolly.mdl
models/props/electrical_box-closed.mdl
models/props/fan_ceiling.mdl
models/props/faucet.mdl
models/props/fire_extinguisher.mdl
models/props/fireextinguisher.mdl
models/props/hang_dryer.mdl
models/props/inbox.mdl
models/props/japanese_toilet.mdl
models/props/katana_stand.mdl
models/props/mop.mdl
models/props/paper_stack.mdl
models/props/plant_potted.mdl
models/props/shower.mdl
models/props/trash_trashcan.mdl
models/tlr_bday/pc.mdl
sound/ambience/de_747_win.wav
sound/ambience/fastline/misc_vendmachine_loop.wav
sound/ambience/trainpass.wav
sound/ambience/watercooler1.wav
sound/ambience/wind2.wav
sound/de_52hours/bee2.wav
sound/de_mangashop/birds3.wav
sound/de_mangashop/birds8.wav
sound/de_mangashop/char/ka1.wav
sound/de_mangashop/char/ka2.wav
sound/de_mangashop/char/nar1.wav
sound/de_mangashop/char/nar2.wav
sound/de_mangashop/char/obama.wav
sound/de_mangashop/char/rl1.wav
sound/de_mangashop/char/sa1.wav
sound/de_mangashop/char/sa2.wav
sound/de_mangashop/char/ss1.wav
sound/de_mangashop/char/ss2.wav
sound/de_mangashop/char/tow1.wav
sound/de_mangashop/char/va1.wav
sound/de_mangashop/char/va2.wav
sound/de_mangashop/char/va3.wav
sound/de_mangashop/char/va4.wav
sound/de_mangashop/char/va5.wav
sound/de_mangashop/char/va6.wav
sound/de_mangashop/copier_amb.wav
sound/de_mangashop/copier_run.wav
sound/de_mangashop/elevmusic.wav
sound/de_mangashop/goomba.wav
sound/de_mangashop/fire3.wav
sound/de_mangashop/flies.wav
sound/de_mangashop/flush6.wav
sound/de_mangashop/kirby_kill.wav
sound/de_mangashop/ko.wav
sound/de_mangashop/policeradio.wav
sound/de_mangashop/sf4.wav
sound/de_mangashop/tkn6.wav
sound/de_mangashop/vomiting.wav
sound/de_mangashop/water_gentle1.wav
sound/expo/street.wav
sound/fan_snd/env.wav
sound/fan_snd/lght.wav
sprites/de_mangashop/bub.spr
sprites/de_mangashop/fire_cz2.spr
sprites/de_mangashop/fire_cz3.spr
sprites/de_mangashop/tkn6.spr
