//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2007 - Infos @ http://www.17buddies.net //
//          More than 15000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
//
// Res file generated by mikado for 17Buddies.
//
// Map Name  : de_tropicpool
//
// Download @: http://dwl.17buddies.net/link/map/7495/de_tropicpool.html
//
//////////////////////////////////////////////////////////
as_tundra.wad
cs_haste.wad
de_vegas.wad
jos.wad
tree.wad
 
gfx/env/egyptup.tga
gfx/env/egyptdn.tga
gfx/env/egyptlf.tga
gfx/env/egyptrt.tga
gfx/env/egyptft.tga
gfx/env/egyptbk.tga

sound/ambience/Birds2.wav
sound/ambience/cricket.wav
sound/ambience/jungle.wav
sound/ambience/music.wav
sound/ambience/summer.wav
sound/ambience/pumper.wav
sound/ambience/drips.wav
sound/ambience/sparks.wav
sound/ambience/computalk2.wav
