//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2007 - Infos @ http://www.17buddies.net //
//          More than 15000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
//
// Res file generated by mikado for 17Buddies.
//
// Map Name  : nbnoobmario_final
//
// Download @: http://dwl.17buddies.net/link/map/16400/nbnoobmario_final.html
//
//////////////////////////////////////////////////////////
gfx/env/trainyardup.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardft.tga
gfx/env/trainyardbk.tga

models/player/gsg9/gsg9.mdl
models/player/guerilla/guerilla.mdl

//sound/ambience/marioxslider.wav
//sound/misc/mariosnowmountain.wav
//sound/misc/mariotheme.wav
//sound/misc/watermario.wav
