// not written by a robot
maps/surf_cyberwave.bsp

gfx/env/arte/surf_cyberwave/sbk.tga
gfx/env/arte/surf_cyberwave/sdn.tga
gfx/env/arte/surf_cyberwave/sft.tga
gfx/env/arte/surf_cyberwave/slf.tga
gfx/env/arte/surf_cyberwave/srt.tga
gfx/env/arte/surf_cyberwave/sup.tga

models/arte/surf_cyberwave/arch_01.mdl
models/arte/surf_cyberwave/cyberwave_title.mdl
models/arte/surf_cyberwave/light_tower_01.mdl
models/arte/surf_cyberwave/light_tower_02.mdl
models/arte/surf_cyberwave/mrcow_title.mdl
models/arte/surf_cyberwave/pillar_tower_01.mdl
models/arte/surf_cyberwave/portal_01.mdl
models/arte/surf_cyberwave/portal_01_p2.mdl
models/arte/surf_cyberwave/ramp_details_01_2.mdl
models/arte/surf_cyberwave/ramp_details_01.mdl
models/arte/surf_cyberwave/ramp_details_02_2.mdl
models/arte/surf_cyberwave/ramp_details_02.mdl
models/arte/surf_cyberwave/ramp_details_03_2.mdl
models/arte/surf_cyberwave/ramp_details_03.mdl
models/arte/surf_cyberwave/s1_end_detail.mdl
models/arte/surf_cyberwave/s1_r010.mdl
models/arte/surf_cyberwave/s1_r011_2.mdl
models/arte/surf_cyberwave/s1_r011.mdl
models/arte/surf_cyberwave/s1_r012_2.mdl
models/arte/surf_cyberwave/s1_r01_2.mdl
models/arte/surf_cyberwave/s1_r012.mdl
models/arte/surf_cyberwave/s1_r013_2.mdl
models/arte/surf_cyberwave/s1_r013.mdl
models/arte/surf_cyberwave/s1_r016.mdl
models/arte/surf_cyberwave/s1_r01.mdl
models/arte/surf_cyberwave/s1_r02.mdl
models/arte/surf_cyberwave/s1_r03.mdl
models/arte/surf_cyberwave/s1_r04_2.mdl
models/arte/surf_cyberwave/s1_r04.mdl
models/arte/surf_cyberwave/s1_r05.mdl
models/arte/surf_cyberwave/s1_r06_2.mdl
models/arte/surf_cyberwave/s1_r06.mdl
models/arte/surf_cyberwave/s1_r07_2.mdl
models/arte/surf_cyberwave/s1_r07.mdl
models/arte/surf_cyberwave/s1_r08_2.mdl
models/arte/surf_cyberwave/s1_r08.mdl
models/arte/surf_cyberwave/s1_r09.mdl
models/arte/surf_cyberwave/s2_end_detail_01.mdl
models/arte/surf_cyberwave/s2_end_detail_02.mdl
models/arte/surf_cyberwave/s2_end_detail_02_p2.mdl
models/arte/surf_cyberwave/s2_r010_2.mdl
models/arte/surf_cyberwave/s2_r010.mdl
models/arte/surf_cyberwave/s2_r012_2.mdl
models/arte/surf_cyberwave/s2_r012.mdl
models/arte/surf_cyberwave/s2_r013_2.mdl
models/arte/surf_cyberwave/s2_r013.mdl
models/arte/surf_cyberwave/s2_r014.mdl
models/arte/surf_cyberwave/s2_r01.mdl
models/arte/surf_cyberwave/s2_r02.mdl
models/arte/surf_cyberwave/s2_r03.mdl
models/arte/surf_cyberwave/s2_r04_2.mdl
models/arte/surf_cyberwave/s2_r04.mdl
models/arte/surf_cyberwave/s2_r05.mdl
models/arte/surf_cyberwave/s2_r07_2.mdl
models/arte/surf_cyberwave/s2_r07.mdl
models/arte/surf_cyberwave/s2_r08_2.mdl
models/arte/surf_cyberwave/s2_r08.mdl
models/arte/surf_cyberwave/s2_r09.mdl
models/arte/surf_cyberwave/skyscraper_01.mdl
models/arte/surf_cyberwave/skyscraper_02.mdl
models/arte/surf_cyberwave/skyscraper_02_r.mdl
models/arte/surf_cyberwave/skyscraper_03.mdl
models/arte/surf_cyberwave/skyscraper_04.mdl
models/arte/surf_cyberwave/skyscraper_05.mdl
models/arte/surf_cyberwave/skyscraper_05_p2.mdl
models/arte/surf_cyberwave/skyscraper_05_p3.mdl
models/arte/surf_cyberwave/skyscraper_05_p4.mdl
models/arte/surf_cyberwave/spawn_lights_01.mdl
models/arte/surf_cyberwave/spawn_lights_02.mdl
models/arte/surf_cyberwave/cyberwaveskybox0.mdl
models/arte/surf_cyberwave/cyberwaveskybox1.mdl