//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2013 - Infos @ http://www.17buddies.net //
//          More than 85000 maps to download!           //
//////////////////////////////////////////////////////////
// Map Name  : xmas_pool_day_b1
// Download @: http://www.17buddies.net/17b2/View/Map/69217/xmas_pool_day_b1.html
// (.res file generated by Santi Concetti with script version 3.0)
//////////////////////////////////////////////////////////
// Wad files legend:
//     *  : Hardcoded in bsp file, this wad was found (in
//          archive or on 17Buddies's website) but doesn't
//          contains any used texture.
//          However, this file may be necessary.
//     ** : Hardcoded in bsp file, this wad could not be
//          found (neither in archive nor on 17Buddies's
//          website) and thus could not be analysed.
//          However, this file may be necessary.
//////////////////////////////////////////////////////////
hlbasics.wad
fypoolday.wad
// fy_snowplace_sym.wad (*)
kaskating.wad
winterxmas.wad
gfx/env/desertup.tga
gfx/env/desertdn.tga
gfx/env/desertlf.tga
gfx/env/desertrt.tga
gfx/env/desertft.tga
gfx/env/desertbk.tga
// models/player/gsg9/gsg9.mdl
// models/player/guerilla/guerilla.mdl
// sound/ambience/sprayer.wav
// sprites/glow04.spr
